"""Add business

Revision ID: 2796a9252a5e
Revises: a72cd928c619
Create Date: 2019-07-18 17:08:48.437416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2796a9252a5e'
down_revision = 'a72cd928c619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('businessID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('managerID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['managerID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('businessID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business')
    # ### end Alembic commands ###
