"""Add Time

Revision ID: 7bb35cf84770
Revises: c3035f09a5b5
Create Date: 2019-07-18 22:44:15.283528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb35cf84770'
down_revision = 'c3035f09a5b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time',
    sa.Column('timeID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('startTime', sa.String(length=40), nullable=False),
    sa.Column('endTime', sa.String(length=40), nullable=False),
    sa.Column('timeTableID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['timeTableID'], ['timeTable.timeTableID'], ),
    sa.PrimaryKeyConstraint('timeID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time')
    # ### end Alembic commands ###
