"""Add TimeTable

Revision ID: c3035f09a5b5
Revises: f13c766c57dd
Create Date: 2019-07-18 22:28:07.998982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3035f09a5b5'
down_revision = 'f13c766c57dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeTable',
    sa.Column('timeTableID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('businessID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['businessID'], ['service.serviceID'], ),
    sa.PrimaryKeyConstraint('timeTableID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timeTable')
    # ### end Alembic commands ###
