"""Add service

Revision ID: f13c766c57dd
Revises: 2796a9252a5e
Create Date: 2019-07-18 17:30:12.049938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f13c766c57dd'
down_revision = '2796a9252a5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('serviceID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('employerID', sa.Integer(), nullable=False),
    sa.Column('businessID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['businessID'], ['business.businessID'], ),
    sa.ForeignKeyConstraint(['employerID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('serviceID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service')
    # ### end Alembic commands ###
